sudo: True

stages:
  - Test
  
  -
dist: trusty

jobs:
  include:
    -
      stage: Test
      language: java
      branches:
        only:
          - master
      jdk: oraclejdk8
      before_install:
        - sudo apt-get update
      script:
        - mvn clean install
        - mvn test -B
